### ISSUE TITLE
Open the frontend in a new window?

### ISSUE THREAD

**Issue by fontanil** [akeeba/skeletonkey#3]
Sorry, perhaps it's not an issue but how to open the site in a new window/tab using an user account from the list of users? 
When I click on an user account to test, the frontend page replaces the administrator page.

Regards,
Robert aka fontanil

**Comment by nikosdion** [comment]
You can't, because of the way this works with single-use, sort-lived, secure hashes, and HTTP-only cookies. Opening a new window would require foregoing one of these security protections which would make effectively create a backdoor to your site.

The best thing you can do is open the Joomla Users page in a new window, then log in as that user.

**Comment by fontanil** [comment]
Thanks, but why not to use the same thing as the "open site" button? Wouldn't that be easier?
![Capture d’écran 2023-01-15 090623](https://user-images.githubusercontent.com/8665970/212529640-f18a42c8-1619-4562-9510-dcdb12ac3aed.jpg)

**Comment by nikosdion** [comment]
As I said, it would be a **SECURITY ISSUE**.

I don't expect you to understand how login security works or why it's necessary to do what I am doing to prevent your site from being hacked but I do expect you to trust me that I do know what I'm doing.
